# Generated by Django 3.0.5 on 2020-04-30 18:16

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Course title')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Сourse start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Course end date')),
                ('finished', models.BooleanField(default=False)),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
